### ISSUE TITLE
Dart Version 2.1 is not compatible with Circular_Chart

### ISSUE THREAD

**Issue by stefanschaller** [xqwzts/flutter_circular_chart#16] opened 2018-08-28 16:14 UTC
I updated my Flutter and your package ist not working with the Dart Version 2.1. See the Screenshot in the extentions. Please fix the Dart SDK Constraints 💃 
<img width="693" alt="unbenannt" src="https://user-images.githubusercontent.com/30521865/44735987-41579f80-aaee-11e8-9f10-9e06b4ea12d8.PNG">

**Comment by Joran-Dob** [comment] 2018-08-28 16:45
Duplicate of #14 ?

**Comment by xqwzts** [comment] 2018-08-30 00:21
Fixed in #17 

I've bumped the sdk constraints to match the ones defined by the latest flutter beta.

A new release is published on pub with that as well: https://pub.dartlang.org/packages/flutter_circular_chart#-installing-tab- - you might need to run `flutter packages upgrade` to get it, or change your pubspec.yaml file to point to ^0.1.0 for this package.

**Closed as completed by xqwzts** 2018-08-30 00:21 UTC
